## Creating Arrays

In [1]:
import numpy as np

In [2]:
array_one = np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [3]:
numberList = [9,8,7,6,]
array_two = np.array(numberList)
array_two

array([9, 8, 7, 6])

In [5]:
array_of_zeros = np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
array_of_ones_int = np.ones((4,5),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [12]:
array_eye = np.eye(5)
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
array_2d = np.array([(2,3,4),(3,5,7)])
array_2d

array([[2, 3, 4],
       [3, 5, 7]])

In [18]:
array_2d.shape

(2, 3)

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
array_nd = np.arange(6).reshape(3,4)
array_nd

ValueError: cannot reshape array of size 6 into shape (3,4)